name: MobRobbers
version: ${project.version}
main: me.advait.mobrobbers.MobRobbers
api-version: 1.16
authors: [Advait]
description: 1/3 mobs will take a random item slot in your inventory and run away with it.
